FROM node:20.10-alpine AS builder

#Add additional packages
RUN apk add --update \
    curl \
    nfs-utils \
    && rm -rf /var/cache/apk/*

# Install app dependencies
WORKDIR /usr/src/app

ADD package.json package-lock.json

# Bundle app source
ADD . /usr/src/app/

ENV NODE_ENV production
ENV PORT 80

ARG SERVER_URL=http://localhost:1337
ENV SERVER_URL=${SERVER_URL}

RUN npm install
# RUN npm install --platform=linuxmusl --arch=x64 sharp
RUN npm run build


FROM node:20.10-alpine AS runner

#Add additional packages
RUN apk add --update \
    bash \
    curl \
    nfs-utils \
    && rm -rf /var/cache/apk/*

ENV NODE_ENV production
ENV PORT 80

ARG SERVER_URL=http://localhost:1337
ENV SERVER_URL=${SERVER_URL}

WORKDIR /usr/src/app

COPY --from=builder /usr/src/app/package.json /usr/src/app/package-lock.json ./
COPY --from=builder /usr/src/app/node_modules ./node_modules/
COPY --from=builder /usr/src/app/ ./

EXPOSE 80


CMD node ./server.js -p 80
