version: '3'
services:
  backend:
    build: .
    container_name: backend
    restart: always
    ports:
      - "1337:1337"
    volumes:
      - .:/app/backend
  frontend:
    build: ../donatello/
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/app/frontend
    environment:
      SERVER_URL: https://funds-be.ndtech.cloud
