name: Deploy to Server

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ vars.DOCKER_REGISTRY_URL }}
        username: ${{ vars.DOCKER_REGISTRY_USERNAME }}
        password: ${{ secrets.DOCKER_REGISTRY_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ vars.DOCKER_REGISTRY_URL }}/${{ vars.DOCKER_REGISTRY_USERNAME }}/backend:latest

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ vars.SSH_USERNAME }}@${{ vars.SSH_IP }} "docker pull ${{ vars.DOCKER_REGISTRY_URL }}/${{ vars.DOCKER_REGISTRY_USERNAME }}/backend:latest && docker run -d -p 1337:1337 ${{ vars.DOCKER_REGISTRY_URL }}/${{ vars.DOCKER_REGISTRY_USERNAME }}/backend:latest"