name: Deploy to Server

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ vars.DOCKER_REGISTRY_URL }}
        username: ${{ vars.DOCKER_REGISTRY_USERNAME }}
        password: ${{ secrets.DOCKER_REGISTRY_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ vars.DOCKER_REGISTRY_URL }}/${{ vars.DOCKER_REGISTRY_USERNAME }}/backend:latest

    - name: Execute remote SSH commands (rebuild)
      uses: appleboy/ssh-action@v1.0.3
      with:    
        host: ${{ vars.SSH_IP }}
        username: ${{ vars.SSH_USERNAME }}
        port: ${{ vars.SSH_PORT }}
        script: |
          docker-compose up -d --build backend